openapi: "3.1.0"
info:
  version: "1.0.0"
  title: Firefly API
  description: REST API for Adobe Firefly for enterprise usage
servers:
  - url: https://firefly-api.adobe.io
 
paths:
  /v2/storage/image:
    $ref: components/paths/upload_image.yaml

components:
  securitySchemes:
    X-ApiKey:
      "type": "apiKey"
      "name": "x-api-key"
      "in": "header"
    Access token:
      "type": "http"
      "scheme": "bearer"